project:
  type: website
  pre-render: python update_date.py
  output-dir: _site
  resources:
    - "attachments/img/"
    - "attachments/pdf/"
  render:
    - "*.qmd"

website:
  title: "Geography"
  navbar:
    background: dark
    logo: logo.png
  page-footer:
    left: |
      <a href="https://creativecommons.org/licenses/by-nc-nd/4.0/"><img src="https://i.creativecommons.org/l/by-nc-nd/4.0/88x31.png" alt="Creative Commons License"></a><br>
      This content is licensed under <a href="https://creativecommons.org/licenses/by-nc-nd/4.0/">CC BY-NC-ND 4.0</a>
    center: |
      &copy; 2026 <a href="https://pulakeshpradhan.github.io/">Pulakesh Pradhan</a><br>
      Last Updated: April 28, 2026

    right: |
      [<i class="bi bi-youtube"></i> YouTube](https://www.youtube.com/@SpatialGeography)

  comments:
    giscus:
      repo: spatialgeography/spatialgeography.github.io
      repo-id: R_kgDOQ3kQ4w
      category: General
      category-id: DIC_kwDOQ3kQ484C7v6Y
      mapping: pathname
      reactions-enabled: true
      loading: lazy

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    toc-depth: 2
    highlight-style: pygments
    code-copy: true
    breadcrumbs: true
    link-external-newwindow: true
    link-external-icon: true
    include-after-body: 
      - print.html
      - search-popup.html
      - visitor-map.html
    other-links:
      - text: Print / Save as PDF
        icon: printer
        href: javascript:window.print()
